#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def _load_summary(path: Path) -> dict[str, str]:
  out: dict[str, str] = {}
  with path.open("r", encoding="utf-8", newline="") as f:
    for r in csv.DictReader(f):
      sample_id = (r.get("sample_id") or "").strip()
      status = (r.get("status") or "").strip()
      hotspot_count = int((r.get("hotspot_count") or "0").strip() or 0)
      hotspot_string = (r.get("hotspot_string") or "").strip()
      if sample_id and status == "ok" and hotspot_count > 0 and hotspot_string:
        out[sample_id] = hotspot_string
  return out


def _update_env(path: Path, hotspots: str) -> bool:
  if not path.exists():
    return False
  lines = path.read_text(encoding="utf-8").splitlines()
  changed = False
  out = []
  for line in lines:
    if line.startswith("HOTSPOTS="):
      out.append(f'HOTSPOTS="{hotspots}"')
      changed = True
    else:
      out.append(line)
  if changed:
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
  return changed


def _update_target_yaml(path: Path, hotspots: str) -> bool:
  if not path.exists():
    return False
  lines = path.read_text(encoding="utf-8").splitlines()
  changed = False
  out = []
  for line in lines:
    if line.startswith("target_hotspots:"):
      out.append(f'target_hotspots: "{hotspots}"')
      changed = True
    else:
      out.append(line)
  if changed:
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
  return changed


def _update_overrides(path: Path, hotspots: str) -> bool:
  if not path.exists():
    return False
  lines = path.read_text(encoding="utf-8").splitlines()
  changed = False
  out = []
  for line in lines:
    if line.startswith("target.target_hotspots="):
      out.append(f"target.target_hotspots='{hotspots}'")
      changed = True
    else:
      out.append(line)
  if changed:
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
  return changed


def _update_bindcraft_json(path: Path, hotspots: str) -> bool:
  if not path.exists():
    return False
  obj = json.loads(path.read_text(encoding="utf-8"))
  if obj.get("target_hotspot_residues") == hotspots:
    return False
  obj["target_hotspot_residues"] = hotspots
  path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
  return True


def _annotate_boltzgen_yaml(path: Path, hotspots: str) -> bool:
  if not path.exists():
    return False
  text = path.read_text(encoding="utf-8")
  marker = "# target_hotspots_from_epitopes:"
  if marker in text:
    lines = text.splitlines()
    out = []
    changed = False
    for line in lines:
      if line.startswith(marker):
        out.append(f'{marker} "{hotspots}"')
        changed = True
      else:
        out.append(line)
    if changed:
      path.write_text("\n".join(out) + "\n", encoding="utf-8")
    return changed
  # append annotation without changing functional spec keys
  text = text.rstrip() + f'\n\n{marker} "{hotspots}"\n'
  path.write_text(text, encoding="utf-8")
  return True


def main() -> int:
  parser = argparse.ArgumentParser(description="Apply extracted epitope hotspots to model_inputs_native.")
  parser.add_argument(
    "--epitope-summary",
    type=Path,
    default=Path(__file__).resolve().parents[2] / "data" / "raw" / "epitopes" / "epitopes_summary.csv",
    help="epitopes summary csv generated by extract_epitopes_from_complexes.py",
  )
  parser.add_argument(
    "--native-root",
    type=Path,
    default=Path(__file__).resolve().parents[2] / "data" / "model_inputs_native",
    help="native inputs root",
  )
  args = parser.parse_args()

  hotspots_map = _load_summary(args.epitope_summary)
  if not hotspots_map:
    raise SystemExit("[ERROR] no eligible samples in epitope summary (need status=ok and hotspot_count>0)")

  updated = {
    "RFantibody": 0,
    "germinal_target_yaml": 0,
    "germinal_overrides": 0,
    "BindCraft": 0,
    "boltzgen_note": 0,
  }
  missed = 0

  for sample_id, hotspots in hotspots_map.items():
    rf_env = args.native_root / "RFantibody" / sample_id / "rfantibody_config.env"
    ge_yaml = args.native_root / "germinal" / sample_id / "target.yaml"
    ge_ovr = args.native_root / "germinal" / sample_id / "run_overrides.txt"
    bc_json = args.native_root / "BindCraft" / sample_id / "settings_target.json"
    bz_yaml = args.native_root / "boltzgen" / sample_id / "design_spec.yaml"

    touched = False
    if _update_env(rf_env, hotspots):
      updated["RFantibody"] += 1
      touched = True
    if _update_target_yaml(ge_yaml, hotspots):
      updated["germinal_target_yaml"] += 1
      touched = True
    if _update_overrides(ge_ovr, hotspots):
      updated["germinal_overrides"] += 1
      touched = True
    if _update_bindcraft_json(bc_json, hotspots):
      updated["BindCraft"] += 1
      touched = True
    if _annotate_boltzgen_yaml(bz_yaml, hotspots):
      updated["boltzgen_note"] += 1
      touched = True

    if not touched:
      missed += 1

  print("[OK] Applied hotspots to native model inputs.")
  print(f"[INFO] eligible_samples={len(hotspots_map)} missed={missed}")
  for k, v in updated.items():
    print(f"[INFO] {k}: {v}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())

